apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Values.ingress.name }}
  annotations:
  {{- range $annotation := .Values.ingress.annotations }}
    {{ $annotation.name }}: {{ $annotation.value }}
  {{- end}}
spec:
  rules:
    - host: {{ .Values.ingress.host.name }}
      http:
        paths:
        {{- range $path := .Values.ingress.host.paths }}
          - path: {{ $path.path }}
            pathType: {{ $path.pathType }}
            backend:
              service:
                name: {{ $.Release.Name }}-{{ $.Values.django.service.name }}
                port:
                  number: {{ $.Values.django.service.port }}
        {{- end}}