apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.django.service.name }}
spec:
  selector:
    app: {{ .Values.django.labels.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.django.service.port }}
      targetPort: {{ .Values.django.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: headless-svc-{{ .Values.postgres.service.name }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.postgres.labels.app}}
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.port }}
