apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentials.name }}
type: {{ .Values.credentials.type }}
data:
  user: {{ .Values.credentials.postgres.user }}
  password: {{ .Values.credentials.postgres.password }}