apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.credentials.name }}
type: {{ .Values.credentials.type }}
data:
  user: {{ .Values.credentials.postgres.user | b64enc}}
  password: {{ .Values.credentials.postgres.password | b64enc}}