apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.django.service.name }}
spec:
  selector:
    app: {{ .Values.django.labels.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.django.container.port }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-{{ .Values.postgres.service.name }}
spec:
  selector:
    app: {{ .Values.django.labels.app }}
    backend: {{ .Values.postgres.labels.backend }}
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.port }}
