apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-{{ .Values.postgres.name }}
spec:
  replicas: {{ .Values.postgres.replicaCount }}
  serviceName: {{ .Values.postgres.serviceName }}
  selector:
    matchLabels:
      app: {{ .Values.postgres.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.labels.app }}
    spec:
      containers:
        - name: {{ .Values.postgres.labels.app }}
          image: {{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          env:
            - name: {{ .Values.postgres.env.db_user}}
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name}}-{{ .Values.credentials.name }}
                  key: {{ .Values.credentials.postgres.user}}
            - name: {{ .Values.postgres.env.db_pass }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name}}-{{ .Values.credentials.name }}
                  key: {{ .Values.credentials.postgres.password}}
            - name: {{ .Values.postgres.env.db_name }}
              value: {{ .Values.postgres.env.name }}
          ports:
            - containerPort: {{ .Values.postgres.port }}
          volumeMounts:
            - name: {{ .Values.postgres.volumeClaim.name }}
              mountPath: {{ .Values.postgres.dataPath }}
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.postgres.volumeClaim.name }}
      spec:
        accessModes:
        {{- range $mode := .Values.postgres.volumeClaim.accessModes }}
          - {{ $mode }}
        {{- end}}
        storageClassName: {{ .Values.resources.storages.postgres.storageClass | quote}}
        resources:
          requests:
            storage: {{ .Values.resources.storages.postgres.capacity }}