kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-{{ .Values.resources.name }}
spec:
  storageClassName: {{ .Values.resources.storages.postgres.storageClass }}
  capacity:
    storage: {{ .Values.resources.storages.postgres.capacity }}
  volumeMode: {{ .Values.resources.storages.postgres.volumeMode }}
  persistentVolumeReclaimPolicy: {{ .Values.resources.storages.postgres.reclaimPolicy }}
  accessModes:
  {{- range $mode := .Values.resources.storages.postgres.accessModes }}
    - {{ $mode }}
  {{- end}}
  hostPath:
    path: {{ .Values.resources.storages.postgres.path }}