kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-data
spec:
  storageClassName: standard
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data